# Generated by Django 4.0.1 on 2022-03-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='on_site',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='res',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='who_orders',
        ),
    ]
