# Generated by Django 4.0.1 on 2022-03-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        ('user', '0002_profile_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.menu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='res',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poll.restaurantlist'),
        ),
    ]
