# Generated by Django 4.0.1 on 2022-03-24 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_site', models.BooleanField(default=0)),
                ('orderer', models.BooleanField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.menu')),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='poll.restaurantlist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
