# Generated by Django 4.0.1 on 2022-03-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_decision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='res_id',
            new_name='res',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='user_id',
            new_name='user',
        ),
    ]
