# Generated by Django 4.0.1 on 2022-03-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_rename_res_id_decision_res_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poll.menu'),
        ),
    ]
