# Generated by Django 4.0.1 on 2022-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_question_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='food',
            field=models.CharField(max_length=256),
        ),
    ]
