# Generated by Django 4.0.1 on 2022-03-24 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_decision_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poll.restaurantlist'),
        ),
    ]
