# Generated by Django 4.0.1 on 2022-03-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='food',
            field=models.TextField(max_length=256),
        ),
    ]
