# Generated by Django 4.0.3 on 2022-03-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_restaurantslist_alter_question_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='food',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='restaurant',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
