# Generated by Django 4.0.1 on 2022-03-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_alter_question_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='restaurant',
            field=models.ForeignKey(default=0, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='poll.restaurantslist'),
        ),
    ]
