# Generated by Django 4.0.1 on 2022-03-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_alter_question_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='restaurant',
            field=models.ForeignKey(default=None, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='poll.restaurantslist'),
        ),
        migrations.AlterField(
            model_name='restaurantslist',
            name='restaurant_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
