# Generated by Django 4.0.1 on 2022-03-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_alter_question_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='restaurant',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.restaurantslist'),
        ),
        migrations.AlterField(
            model_name='restaurantslist',
            name='restaurant_name',
            field=models.CharField(max_length=30),
        ),
    ]
